spring.application.name=LLMToolsForSpreadsheets
spring.main.web-application-type=none

# OpenAI API Configuration
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.api-key=
spring.ai.openai.chat.options.model=gpt-5.2
spring.ai.openai.chat.options.temperature=0.7
# spring.ai.openai.chat.options.max-completion-tokens=16384 # for gpt-4o
# spring.ai.openai.chat.options.max-completion-tokens=128000 # for gpt-5.2 
# http-client.read-timeout-seconds=300

# proxy
proxy.enabled=false
proxy.host=
proxy.port=
proxy.username=
proxy.password=

# logging
logging.level.root=INFO
logging.level.reactor.netty=INFO
logging.level.org.springframework.web=INFO
logging.level.moros.asf.tools.forspreadsheets=INFO
# logging.file.name=llm_tools.log

# applications
asf.auto-completion.enabled=true
asf.auto-completion.columns=uuid:uuid,created-at:current-datetime,updated-at:current-datetime
asf.auto-completion.gpt-ignore-columns=created-at,updated-at
asf.auto-update.enabled=true
asf.auto-update.columns=updated-at:current-datetime
asf.auto-update.gpt-ignore-columns=updated-at
asf.version=0.1.1
asf.title=AI Software Factory Tools
